version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.36
    environment:
      - MYSQL_DATABASE=exam
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql  
  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/exam?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
volumes:
  mysql:
