version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.36
    environment:
      - MYSQL_DATABASE=exam
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./exam_db.sql:/docker-entrypoint-initdb.d/init.sql  # Gắn file SQL export vào container

  spring-app:
    container_name: exam_project
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/exam?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - SPRING_AI_OPENAI_API_KEY=${OPENAI_API_KEY}
volumes:
  mysql:
